name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Create docs folder
        run: mkdir -p docs

      - name: Package Helm chart
        run: helm package charts/mychart --destination docs

      - name: Update Helm repo index
        run: |
          helm repo index docs --url https://Tan-tan-san.github.io/helm-charts

      - name: Commit packaged chart and index
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Update Helm chart and index"
          git push
